version: '2'

services:
    nginx:
        build: ./docker/nginx
        ports:
            - "8080:80"
        volumes:
            - .:/code
        networks:
            - code-network
    php:
        build: ./docker/php
        volumes:
            - .:/code
        networks:
            - code-network
        links:
            - postgres:db
    npm:
        image: node:7.10
        volumes:
            - .:/code
        working_dir: /code/client-app
        networks:
            - code-network
    composer:
        image: dylanlindgren/docker-laravel-composer
        volumes:
            - .:/code
        working_dir: /code
        networks:
            - code-network
    artisan:
        image: dylanlindgren/docker-laravel-artisan
        volumes:
            - .:/code
        working_dir: /code
        networks:
            - code-network
        links:
            - postgres:db
    postgres:
        image: postgres:9.6.1
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: secret
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
